name: Scala CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
#      - name: Trigger antlr plugin to generate java files
#        run: sbt buildAllMixQLCore #temp fix: call buildAllMixQLCore to generate antlr java files
      - name: Run tests
        run: sbt coverage buildAllMixQLCore test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
      - name: Formatting
        run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
